site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
nav:
    - 0 - Introduction: index.md
    - 1 - Install Editor: editor-install.md
    - HTML: 
        - Intro: html-guide/01-html-intro.md
        - Understand HTML: html-guide/02-understand-basic-html.md
        - Play with HTML: html-guide/03-play-with-html.md
    - CSS:
        - Intro: css-guide/01-intro.md
        - there-are-3-writing-styles: css-guide/there-are-3-writing-styles.md
        - Class and ID: css-guide/02-class-and-id.md
        - Google Dev Tools: css-guide/03-google-dev-tools.md
        - Complex CSS: css-guide/04-complex-css.md
    - Bootstrap CSS:
        - Intro: bootstrap-css-guide/01-intro.md
        - Play with Bootstrap CSS: bootstrap-css-guide/02-play-with-bootstrap.md
        - Bootstrap Component: bootstrap-css-guide/03-component.md
        - Combine with Custom CSS: bootstrap-css-guide/04-combine-with-custom-css.md
        - Check examples page: bootstrap-css-guide/05-check-examples-page.md
    - Javascript:
        - Intro: javascript-guide/intro.md
        - play-with-javascript: javascript-guide/play-with-javascript.md
        - 3-writing-styles: javascript-guide/3-writing-styles.md
    - jQuery:
        - Intro: jquery-guide/intro.md
        - Repalce javascript: jquery-guide/play-with-jquery.md
    - Bootstrap JS:
        - Intro: bootstrap-js-guide/01-intro.md
        - Manual JS: bootstrap-js-guide/02-manual-js.md
    - Combine all front end:
        - Intro: combine-front-end-guide/intro.md
        - Tutorial: combine-front-end-guide/tutorial.md
        - jQuery-back-to-top: combine-front-end-guide/jquery-back-to-top.md
        - deploy: combine-front-end-guide/deploy.md
    - Recap Front End: recap-frontend.md
    - Coffee Break 1: coffee-break1.md
    - Git:
        - Intro: git-guide/intro.md
        - Benefit of Git: git-guide/benefit.md
    - Rails Basics:
        - Chapter Intro: rails-guide-basics/chapter-intro.md
        - Chapter01 Setup application: rails-guide-basics/chapter01.md
        - Chapter02: rails-guide-basics/chapter02.md
        - Chapter03: rails-guide-basics/chapter03.md
        - Chapter04: rails-guide-basics/chapter04.md
        - Chapter05: rails-guide-basics/chapter05.md
        - Chapter06: rails-guide-basics/chapter06.md
        - Chapter07: rails-guide-basics/chapter07.md
        - Chapter08: rails-guide-basics/chapter08.md
        - Chapter09: rails-guide-basics/chapter09.md
        - Chapter10: rails-guide-basics/chapter10.md
        - Chapter11: rails-guide-basics/chapter11.md
        - Chapter12: rails-guide-basics/chapter12.md
        - Chapter13: rails-guide-basics/chapter13.md
        - Chapter14: rails-guide-basics/chapter14.md
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite
  - admonition